import streamlit as st
import numpy as np
import math
import matplotlib.pyplot as plt
import importlib.util
import sys

# Page configuration
st.set_page_config(
    page_title="Blood Flow Simulation Suite",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Sidebar navigation
st.sidebar.markdown("# 🏥 Navigation")
page = st.sidebar.radio(
    "Select a Simulation:",
    [
        "🏠 Home",
        "🫀 Simulation T (Time-based)",
        "🌊 Simulation Z (Space-based)",
        "💚 Healthy Artery Model",
        "🧪 Test 1-T (Cosine Bump)",
        "🧪 Test 1-Z (Spatial)",
        "🧪 Dimensionless Model"
    ]
)

# ============================================================
# HOME PAGE
# ============================================================
if page == "🏠 Home":
    st.title("🫀 Blood Flow Simulation Suite")
    st.markdown("---")
    
    st.markdown("""
    Welcome to the **Blood Flow Simulation Suite**! This platform provides interactive simulations 
    of cardiovascular hemodynamics using advanced mathematical models of arterial blood flow.
    """)
    
    st.subheader("📚 Available Simulations")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.info("""
        **🫀 Simulation T (Time-based)**
        
        Models blood pressure and flow propagation through an artery over time using the 1D blood 
        flow equations with MacCormack numerical scheme.
        
        ✅ Available for cloud deployment
        """)
        
        st.info("""
        **🌊 Simulation Z (Space-based)**
        
        Interactive visualization showing spatial distribution of pressure, flow, and area 
        along the artery at different time snapshots.
        
        ⚠️ Local execution recommended
        """)
    
    with col2:
        st.info("""
        **💚 Healthy Artery Model**
        
        Advanced model including Windkessel outlet boundary conditions 
        for realistic downstream compliance effects.
        
        ⚠️ Local execution recommended
        """)
        
        st.info("""
        **🧪 Test Simulations**
        
        Various test cases for validation and verification purposes.
        
        ⚠️ Local execution recommended
        """)
    
    st.markdown("---")
    st.subheader("🚀 Getting Started")
    st.markdown("""
    1. Select a simulation from the navigation menu
    2. Adjust the arterial parameters using the sliders
    3. Click "Run Simulation" to start
    4. View results in interactive plots and summary statistics
    """)

# ============================================================
elif page == "🫀 Simulation T (Time-based)":
    st.title("🫀 Simulation T: Time-Based Blood Flow Analysis")
    st.markdown("This simulation uses the original backend code for results.")
    # Import and run original simulation_t.py
    spec = importlib.util.spec_from_file_location("simulation_t", "simulation_t.py")
    sim_t = importlib.util.module_from_spec(spec)
    sys.modules["simulation_t"] = sim_t
    spec.loader.exec_module(sim_t)
    # Display results using original code outputs
    st.markdown("**Results are generated by the original simulation_t.py code.**")
    st.pyplot = st.pyplot  # for compatibility
    # The original code runs and shows plots directly
    # Optionally, you can re-run the code and capture the plots if needed
    st.info("Run simulation_t.py directly for full output.")

# ============================================================
elif page == "🌊 Simulation Z (Space-based)":
    st.title("🌊 Simulation Z: Space-Based Analysis")
    st.markdown("This simulation uses the original simulation_z.py backend code for results.")
    # Import and run original simulation_z.py
    spec = importlib.util.spec_from_file_location("simulation_z", "simulation_z.py")
    simz_mod = importlib.util.module_from_spec(spec)
    sys.modules["simulation_z"] = simz_mod
    spec.loader.exec_module(simz_mod)
    st.markdown("**Results are generated by the original simulation_z.py code.**")
    st.info("Run simulation_z.py directly for full output.")

# ============================================================
elif page == "💚 Healthy Artery Model":
    st.title("💚 Healthy Artery Model")
    st.markdown("This simulation uses the original healthy_with_windkessel.py backend code for results.")
    # Import and run original healthy_with_windkessel.py
    spec = importlib.util.spec_from_file_location("healthy_with_windkessel", "healthy_with_windkessel.py")
    healthy_mod = importlib.util.module_from_spec(spec)
    sys.modules["healthy_with_windkessel"] = healthy_mod
    spec.loader.exec_module(healthy_mod)
    st.markdown("**Results are generated by the original healthy_with_windkessel.py code.**")
    st.info("Run healthy_with_windkessel.py directly for full output.")

# ============================================================
elif page == "🧪 Test 1-T (Cosine Bump)":
    st.title("🧪 Test 1-T: Cosine Bump Validation")
    st.markdown("This test uses the original C5_test1_t.py backend code for results.")
    # Import and run original C5_test1_t.py
    spec = importlib.util.spec_from_file_location("C5_test1_t", "C5_test1_t.py")
    test1t_mod = importlib.util.module_from_spec(spec)
    sys.modules["C5_test1_t"] = test1t_mod
    spec.loader.exec_module(test1t_mod)
    st.markdown("**Results are generated by the original C5_test1_t.py code.**")
    st.info("Run C5_test1_t.py directly for full output.")

# ============================================================
elif page == "🧪 Test 1-Z (Spatial)":
    st.title("🧪 Test 1-Z: Spatial Distribution Test")
    st.markdown("This test uses the original C5_test1_z.py backend code for results.")
    # Import and run original C5_test1_z.py
    spec = importlib.util.spec_from_file_location("C5_test1_z", "C5_test1_z.py")
    test1z_mod = importlib.util.module_from_spec(spec)
    sys.modules["C5_test1_z"] = test1z_mod
    spec.loader.exec_module(test1z_mod)
    st.markdown("**Results are generated by the original C5_test1_z.py code.**")
    st.info("Run C5_test1_z.py directly for full output.")

# ============================================================
elif page == "🧪 Dimensionless Model":
    st.title("🧪 Dimensionless Model: K1=0 Damping Test")
    st.markdown("This test uses the original Dimentionless_test-t_slider.py backend code for results.")
    # Import and run original Dimentionless_test-t_slider.py
    spec = importlib.util.spec_from_file_location("Dimentionless_test_t_slider", "Dimentionless_test-t_slider.py")
    dim_mod = importlib.util.module_from_spec(spec)
    sys.modules["Dimentionless_test_t_slider"] = dim_mod
    spec.loader.exec_module(dim_mod)
    st.markdown("**Results are generated by the original Dimentionless_test-t_slider.py code.**")
    st.info("Run Dimentionless_test-t_slider.py directly for full output.")
